version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data:/var/lib/rabbitmq/
        - ./data:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin

networks:
  rabbitmq_go_net:
    driver: bridge